//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvancedWebProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdvancedWebDevelopmentEntities1 : DbContext
    {
        public AdvancedWebDevelopmentEntities1()
            : base("name=AdvancedWebDevelopmentEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cart> Cart { get; set; }
        public virtual DbSet<Cart_Items> Cart_Items { get; set; }
        public virtual DbSet<CustomerData> CustomerData { get; set; }
        public virtual DbSet<ProductInfo> ProductInfo { get; set; }
    }
}
